### ISSUE TITLE
The user options minATractSep and maxATractSep aren't used

### ISSUE THREAD

**Issue by johnsonra** [abcsFrederick/non-B_gfa#4]
Found another bug. The user options minATractSep and maxATractSep aren't used anywhere. Instead, the default values are essentially hardwired into this line:
`if ((distToNext <= 11.1) && (distToNext >= 9.9))`

_Originally posted by @rsharris in https://github.com/abcsFrederick/non-B_gfa/issues/2#issuecomment-626339342_

**Comment by johnsonra** [comment]
@rsharris, your attention to detail is appreciated. Feel free to issue a pull request to fix this one if we take too long to address it. Thanks for the code review!

**Comment by rsharris** [comment]
I'm good — I'm actually not using the program directly. Instead, a colleague has used the program to identify A-phased repeats, has filtered them (based on some other genomic feature), and then wants to partition the APRs into A-tracts. I was asked to implement that partitioning.

I had difficulty finding a clear definition of an A-tract suitable for implementation. That's why I ended up digging into the source code. I added a lot of debug prints to findAPR.c to try to understand how it called A-tracts, which is how I ended up noticing the issues I've reported.

Much of the source code is clearer than a lot of other bioinformatics tools. But I still wasn't able to come up with a clear sense of what constituted an A-tract. Part of that is due to a lack of confidence that the code correctly implements the tract definition at the top of findAPR.c. (It might, but I couldn't tell).

In the end though, while I wasn't able to glean a clear definition from the source code, I have solved my problem by converting part of the getAtracts() function to python and incorporating that into my tool. I've attributed this repo and the Cer et al 2012 paper in my tool. I believe this is fair use, but please let me know if you think otherwise.

I'm not particularly happy with this as a solution — from a software maintenance standpoint it is brittle. But it seems like the best solution in the short term, to get my colleague past his hurdle.

**Comment by Brian-Luke** [comment]
We thank you for your examination and it is clear that the author of this module did not have a clear definition of an A-tract. We are currently constructing a detailed definition and will change the code to reflect this once completed.  We will probably remove minATractSep  and maxATractSep since the A-track phasing should be 10 or 11 bp and we don't want the user to modify these values and getting results that cannot be explained.
